### ISSUE TITLE
Crashes when connecting

### ISSUE THREAD

**Issue by micah686** [Yink/Amadeus#39]
On build 0.8.9-beta.7, it crashes when connecting. Sometimes it crashes and you can see Kurisu in the background, and sometimes it just crashes without showing that.
The previous version of the app works fine.

Running it on a Nexus 5X, on android 6.0.1
If there is a debug log, tell me where it is, and I'll upload it as well.

On a side note, it doesn't seem to respect the audio volume settings

**Comment by RIP95** [comment]
Experienced same problem after [this commit](https://github.com/Yink/Amadeus/commit/5cd4d02bf8e887d9fd9651fdc3b923210cc00c18). Probably latest build hasn't been updated yet, but it was fixed in later commit. Try my testing [build].(https://github.com/RIP95/Amadeus/releases/tag/0.8.9-test)

**Comment by Yink** [comment]
Thank you for your report; I will update the release as soon as I come home. Please report if you have any further issues.

**Comment by micah686** [comment]
That test build seemed to fix it. Thanks.

**Comment by Yink** [comment]
Perfect, released the new version now.
