### ISSUE TITLE
Google App wasn't detected.

### ISSUE THREAD

**Issue by chestnutme** [Yink/Amadeus#49]
The Google Service Framework / Google Play Service / Google Play Store are running well on my phone.But the Amadeus launcher page warns that Google App wasn't detected.Should I install some other extra google app?
Thanks.

**Comment by Yink** [comment]
Did you install [this](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)?

**Comment by chestnutme** [comment]
Problem Solved!I installed the Google App and connected to Kurisu successfully.
Thanks for your answer!
