### ISSUE TITLE
Kurisu can't hear me.

### ISSUE THREAD

**Issue by leorarity** [Yink/Amadeus#52]
Google app is installed, and can detect my voices.
android 6.0.1
phone is xiaomi's redmi note 4x
i give permission to record voice already
is there anything else that i can do to let her listen to me:( 
also i can long tap to let her speak random
but when i short tap, there is no beep sound and no matter what i say she does not reply, and if i tap again she will say 'sorry'

**Comment by Yink** [comment]
Hi and thank you for stating your problem. Unfortunately I have no idea at the moment on what could be causing your problem, but it seems that Amadeus fails to call the Google App. Have you tried reinstalling both? If you want to make sure, you can install logcat (included in Android Studio for example) to read out the logs.

I hope we can fix your problem!

**Comment by leorarity** [comment]
unfortunately reinstall doesnt work😭 i do feel that it's becoz that amadeus is not connected to google, although the app never say 'google app not decteted'. anything else i can do now? i dont get how to use the logcat tho sorry

**Comment by Yink** [comment]
Hm, I'll try to replicate the issue on my end, but for now I don't know what could be causing the problem for you, sorry. Maybe some other users have the same problem and can help there.

**Comment by Nadeem-Mohammad-Sinuous-Mocha** [comment]
Leorarity How did set your default voice recorder as the google app? Cant find a way to do it.

**Comment by Mk-Chan** [comment]
It's settings->Apps->Defaults->Assist&Voice Input for me.

**Comment by SinuousMocha** [comment]
Thanks, I Got it as my default now, though Im still having the issue where she cant hear me :(

**Comment by SinuousMocha** [comment]
Im using a Galaxy S8 with Android version 8.0.0
