### ISSUE TITLE
Settings Wont Open

### ISSUE THREAD

**Issue by bobeable** [Yink/Amadeus#56]
Sorry to disturb you, but when I tap on the logo instead of showing settings it just shows a blank screen. Is there any troubleshoot for this problem or is it just my device?

**Comment by Yink** [comment]
Which android version are you on and have you tried restarting and reinstalling?

**Comment by bobeable** [comment]
2.3 android version, and yes I have reinstalled it and had the same result

**Comment by Yink** [comment]
I fear the only solution is to upgrade your android version, but I will look into it some more.

**Comment by bobeable** [comment]
I can't update any further because it is an old device, but thank you anyway
