### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by Zerosuzuha** [Yink/Amadeus#59]
Hi, may i know source code use for what ? How i gotta to use it ? Extra it to android/data or obb or what ?

**Comment by Yink** [comment]
Hi, what do you want to do? If you just want the app, head over to "releases" and download the .apk from there.

**Comment by Zerosuzuha** [comment]
About apk, i already download and installed. I just curious about what use
of source code coz u put it at page.

**Comment by Yink** [comment]
Github is a version control software primarily for source code, that's why the source code is on here.

**Comment by Zerosuzuha** [comment]
Last question, so, i don't need to download source code, only download apk, right ? Thanks for your patience. I hope we can have more interactive with Amadeus. Also, i wish you all can have Amade Suzuha Amadeus soon. I Wait for your good new.^^Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [Yink/Amadeus] source code (#59)From: Nils To: Yink/Amadeus CC: Zerosuzuha ,Author Github is a version control software primarily for source code, that's why the source code is on here.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Yink/Amadeus","title":"Yink/Amadeus","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Yink/Amadeus"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Yink in #59: Github is a version control software primarily for source code, that's why the source code is on here."}],"action":{"name":"View Issue","url":"https://github.com/Yink/Amadeus/issues/59#issuecomment-385233813"}}}

**Comment by Yink** [comment]
Correct, you only need the .apk. And thank you for your suggestions! I hope you have fun with the app.
